// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../src/components/system/AppLoading.vue')['default']
    FlexSpace: typeof import('./../src/components/common/FlexSpace.vue')['default']
    IconHoverContainer: typeof import('@/layout/components/Header/components/IconHoverContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/common/SvgIcon.vue')['default']
  }
}
